spring.application.name=CompanyMicroservices
server.port=8081


#h2 config
#spring.application.name=JobApp
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update


#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=jobMS
spring.datasource.password=Msjob
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database.platform=org.hibernate.dialect.PostgreSQLDialect
